//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BooksResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BooksResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication2.BooksResource", typeof(BooksResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;catalog&gt;
        ///   &lt;book id=&quot;B1&quot;&gt;
        ///      &lt;author&gt;Kutner, Joe&lt;/author&gt;
        ///      &lt;title&gt;Deploying with JRuby&lt;/title&gt;
        ///      &lt;genre&gt;Computer&lt;/genre&gt;
        ///      &lt;price&gt;33.00&lt;/price&gt;
        ///      &lt;publish_date&gt;2012-08-15&lt;/publish_date&gt;
        ///      &lt;description&gt;Deploying with JRuby is the missing link between enjoying JRuby and using it in the real world to build high-performance, scalable applications.&lt;/description&gt;
        ///   &lt;/book&gt;
        ///   &lt;book id=&quot;B2&quot;&gt;
        ///      &lt;author&gt;Ralls, Kim&lt;/author&gt;
        ///      &lt;title&gt;Midnight Rain&lt;/title&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string books {
            get {
                return ResourceManager.GetString("books", resourceCulture);
            }
        }
    }
}
